on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]
    
jobs:
  get-secret:
    runs-on: ubuntu-latest

    steps:

      - name: Print secretITO
        env:
          SECRET: ${{ secrets.SONAR_TOKEN }}
        run: echo $SECRET
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test


